#!/usr/bin/env bash
mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua

cd /home/chris/.config/nvim
rm /home/chris/.config/nvim/init.vim
rm -rf /home/chris/.config/nvim/plugin/*
rm -rf /home/chris/.config/nvim/after/plugin/*
rm -rf /home/chris/.config/nvim/lua/*
ln -s /home/chris/.dotfiles/neovim/init.vim ./

for f in /home/chris/.dotfiles/neovim/plugin/*; do
    cd /home/chris/.config/nvim/plugin/
    ln -s $f ./
done

for f in /home/chris/.dotfiles/neovim/after/plugin/*; do
    cd /home/chris/.config/nvim/after/plugin/
    ln -s $f ./
done

for f in /home/chris/.dotfiles/neovim/lua/*; do
    cd /home/chris/.config/nvim/lua/
    ln -s $f ./
done


